get http://localhost:3000/items/all
Accept: application/json, */*
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik5UZ3dORUV5TVRJd05FWTBORGM0UVVaRFJEQTFSall3TkRZMU1rWkJOa0V5UmtVd09FRkZPQSJ9.eyJodHRwczovL3Nzby1hcGkuZGVtby5jb20vcm9sZXMiOlsibWVudS1hZG1pbiJdLCJpc3MiOiJodHRwczovL21vYmVlLmF1dGgwLmNvbS8iLCJzdWIiOiJzYW1scHxvbmVsb2dpbnxsb2Rvbm5lbGxAd2lzZXIuY29tIiwiYXVkIjpbImh0dHBzOi8vc3NvLWFwaS5kZW1vLmNvbSIsImh0dHBzOi8vbW9iZWUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTU3Njc5MjIyMSwiZXhwIjoxNTc2ODc4NjIxLCJhenAiOiJlYWgwVWQycUxwSlg2V0hQMGRCQTNnZDNGRlNyWmFNTiIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJwZXJtaXNzaW9ucyI6WyJjcmVhdGU6aXRlbXMiLCJkZWxldGU6aXRlbXMiLCJyZWFkOml0ZW1zIiwidXBkYXRlOml0ZW1zIl19.yHBjsHAQm_9pfZfrNJ2EPrqGwxzO5qhfSygEZqoDEoAq7Q3HedU_LUvJexRq80snZE3ZmZBlzTapS50cdKk0wJmdyfvJ7NPeMbxtdJ_vRToYWJmM7USzQvwTmsHHvw_bVX1CnPAXBpcxfOwquytM_qh_5SKeavUEY6-KHVSV2Ae6bVORXI1EssWMpnCALOhYv1iC1KFMPVNbT6r5nkU4jGra1k4MUT4tdUGlJcF3juiiyyOO9KUi6h7ho6lAvevBHqqX_ogeinpx8OGPlni0uhHF9DnSxcjEUG18NeusJgfoXPgsklrdoIMmE5pVI3wO6pmkxXs7BJb3ndKo5Squ9g