# Documentation
# https://docs.docker.com/compose/compose-file

version: '3'

services:

  app:
    image: node:erbium-alpine
    restart: always
    working_dir: /app
    command:
      - yarn
      - start:debug
    env_file:
      - "./.env"
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - $PWD:/app
    networks:
      - backend

networks:
  backend:
    driver: bridge
